---
title: "Streaming Service Success: an Analysis on Netflix Data"
author: "Talyah Greyling"
date: "`r Sys.Date()`"
bibliography: Tex/ref.bib       
output:
  pagedown::html_paged:
    # template: wp_paged.html
    # css: ['wp.css', 'wp-fonts.css', 'wp-page.css']
    css: ["Template/default-fonts-Texevier.css", "Template/default-page-Texevier.css", "Template/default-Texevier.css"]
    csl: Template/harvard-stellenbosch-university.csl # referencing format used.
    template: ["Template/paged-Texevier.html"]

    toc: false
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: TRUE
    
abstract: |
    This html document contains an analysis of Netflix data to uncover the dos and don'ts of streaming services. Key statistics, graphs and tables are accompanied by short summaries ideal for any busy investor to make quick & efficient investment calls. 

---

```{r setup, include = FALSE}

# Housekeeping 
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos = 'H') # set chunk defaults 
rm(list = ls()) # clear environment 
options(scipen = 999) #suppress scientific notation

# Source all existing functions 
list.files('..//Question1/code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))
list.files('..//Question2/code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))
list.files('code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))

# Set theme & colour palette
palette <- c("#3A7370", "#FB9072", "#FFC57B", "#CE677A", "#163940", "#2C1F2C")
theme <- set_custom_theme()

# Load neccessary libraries 
pacman::p_load(dplyr, ggplot2, tidyverse, stringr) ############## update 

# Load data 
location <- "data/netflix/"
df_titles <- read_rds(glue::glue("{location}titles.rds"))
df_credits <- read_rds(glue::glue("{location}credits.rds"))
df_movies <-  read_csv(glue::glue("{location}netflix_movies.csv"))
HBO_titles <- read_rds("..//Question1/data/US_Baby_names/HBO_titles.rds")

```
\newpage 

```{r formatting data}

# Identify main genre (assume first genre listed)  
df_titles <- df_titles %>% 
    mutate(main_genre = sub(",.*", "", genres)) %>% 
    mutate(main_genre = gsub("\\[|\\]|'", "", main_genre))

# Generate genre distribution
genre_distribution <- df_titles %>%
  group_by(main_genre) %>%
  summarise(count = n()) %>% 
  filter(main_genre != "")

# Calculate top 10 genres by average audience score
top_10_genres <- HBO_titles %>%
  group_by(Genre) %>%
  summarise(AvgScore = mean(`Audience  score %`, na.rm = TRUE)) %>%
  arrange(desc(AvgScore)) %>%
  head(10)

```



